// Import necessary Sequelize components - Sequelize and DataTypes
const { Sequelize, DataTypes } = require('sequelize');

// Import the Sequelize instance (initialized connection to the database) from the '../config/database' file
const db = require('../config/database');

// Define the Game model using Sequelize's define method
const Game = db.define('Game', {
  // Define the 'id' field with type UUID, a default value generated by UUIDV4, and set it as the primary key
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true,
  },

  // Define the 'name' field with type STRING, and it cannot be null
  name: {
    type: DataTypes.STRING,
    allowNull: false,
  },

  // Define the 'description' field with type TEXT, and it cannot be null
  description: {
    type: DataTypes.TEXT,
    allowNull: false,
  },

  // Define the 'picture' field with type STRING, assuming it stores the image URL
  picture: {
    type: DataTypes.STRING,
  },

  // Define the 'quantity' field with type INTEGER, and it cannot be null
  quantity: {
    type: DataTypes.INTEGER,
    allowNull: false,
  },

  // Define the 'price' field with type FLOAT, and it cannot be null
  price: {
    type: DataTypes.FLOAT,
    allowNull: false,
  },

  // Define the 'isactive' field with type STRING, default value is 'Y' (assuming true or available)
  isactive: {
    type: DataTypes.STRING,
    allowNull: false,
    defaultValue: 'Y',
  },

  // Define the 'user_id' field with type UUID, and it cannot be null. It references the 'id' in the 'users' table
  user_id: {
    type: DataTypes.UUID,
    allowNull: false,
    references: {
      model: 'users', // Name of the referenced table
      key: 'id',      // Primary key of the referenced table
    },
  },

  // Define 'created_at' and 'updated_at' fields with type DATE, specifying the field names in the database
  created_at: {
    type: DataTypes.DATE,
    field: 'created_at',
  },
  updated_at: {
    type: DataTypes.DATE,
    field: 'updated_at',
  }
}, {
  // Sequelize model configuration options:

  // Disable timestamps (created_at and updated_at) since 'created_at' and 'updated_at' fields are explicitly defined
  timestamps: false,

  // Use underscored naming (e.g., snake_case) for automatically added fields like foreign keys
  underscored: true,

  // Set the table name to 'games'
  tableName: 'games',
});

// Export the Game model for use in other parts of your application
module.exports = Game;
