// Import necessary Sequelize components - Sequelize and DataTypes
const { Sequelize, DataTypes } = require("sequelize");

// Import the Sequelize instance (initialized connection to the database) from the '../config/database' file
const db = require("../config/database");
const { ORDER_STATUS } = require("../utils/constants");

// Define the Game model using Sequelize's define method
const Order = db.define(
  "Order",
  {
    // Define the 'id' field with type UUID, a default value generated by UUIDV4, and set it as the primary key
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },

    user_id: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: "users", // Name of the referenced table
        key: "id", // Primary key of the referenced table
      },
    },

    status: {
      type: DataTypes.STRING,
      allowNull: false,
      defaultValue: ORDER_STATUS.PENDING,
    },

    subtotal: {
      type: DataTypes.FLOAT,
      allowNull: false,
      defaultValue: 0.0,
    },

    discount: {
      type: DataTypes.FLOAT,
      allowNull: false,
      defaultValue: 0.0,
    },

    coupon_id: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: "coupons", // Name of the referenced table
        key: "id", // Primary key of the referenced table
      },
    },

    tax_id: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: "taxes", // Name of the referenced table
        key: "id", // Primary key of the referenced table
      },
    },

    grand_total: {
      type: DataTypes.FLOAT,
      allowNull: false,
      defaultValue: 0.0,
    },

    shipping_address_id: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: "shipping_addresses", // Name of the referenced table
        key: "id", // Primary key of the referenced table
      },
    },

    billing_address_id: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: "billing_addresses", // Name of the referenced table
        key: "id", // Primary key of the referenced table
      },
    },

    created_at: {
      type: DataTypes.DATE,
      field: "created_at",
    },
    updated_at: {
      type: DataTypes.DATE,
      field: "updated_at",
    },
  },
  {
    // Sequelize model configuration options:

    // Disable timestamps (created_at and updated_at) since 'created_at' and 'updated_at' fields are explicitly defined
    timestamps: false,

    // Use underscored naming (e.g., snake_case) for automatically added fields like foreign keys
    underscored: true,

    // Set the table name to 'games'
    tableName: "orders",
  }
);

// Export the Game model for use in other parts of your application
module.exports = Order;
