// Import necessary Sequelize components - Sequelize and DataTypes
const { Sequelize, DataTypes } = require('sequelize');

// Import the Sequelize instance (initialized connection to the database) from the '../config/database' file
const db = require('../config/database');

// Define the User model using Sequelize's define method
const User = db.define('User', {
  // Define the 'id' field with type UUID, a default value generated by UUIDV4, and set it as the primary key
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true,
  },

  // Define the 'full_name' field with type STRING, and it cannot be null
  full_name: {
    type: DataTypes.STRING,
    allowNull: false,
  },

  // Define the 'email' field with type STRING, and it cannot be null
  email: {
    type: DataTypes.STRING,
    allowNull: false,
  },

  // Define the 'password' field with type TEXT, and it cannot be null
  password: {
    type: DataTypes.TEXT,
    allowNull: false,
  },

  // Define the 'username' field with type STRING
  username: {
    type: DataTypes.STRING,
  },

  role: {
    type: DataTypes.STRING,
    defaultValue: 'user',
  },

  // Define the 'phone_number' field with type STRING
  phone_number: {
    type: DataTypes.STRING,
  },

  // Define the 'address' field with type STRING
  address: {
    type: DataTypes.STRING,
  },

  // Define the 'is_active' field with type STRING, default value is 'Y' (assuming true or available)
  is_active: {
    type: DataTypes.STRING,
    allowNull: false,
    defaultValue: 'Y',
  },

  // Define 'created_at' and 'updated_at' fields with type DATE, specifying the field names in the database
  created_at: {
    type: DataTypes.DATE,
    field: 'created_at',
  },
  updated_at: {
    type: DataTypes.DATE,
    field: 'updated_at',
  }
}, {
  // Sequelize model configuration options:

  // Disable timestamps (created_at and updated_at) since 'created_at' and 'updated_at' fields are explicitly defined
  timestamps: false,

  // Use underscored naming (e.g., snake_case) for automatically added fields like foreign keys
  underscored: true,

  // Set the table name to 'users'
  tableName: 'users',
});

// Export the User model for use in other parts of your application
module.exports = User;
